Various GBA Fixes - Pre NDS port
pinobatch/240p-test-mini pull request #52
Opened 2024-03-17 07:44 UTC by Lorenzooone

2024-03-17 14:11 UTC, pinobatch requested changes
If we're generating two files when converting an asset, we'll need to ensure the conversion is safe for parallel builds. Make has some quirks about this.

2024-03-17 14:11 UTC, pinobatch commented on gba/Makefile
> +helppages.s helppages.h: helppages.txt last-commit ../tools/paginate_help.py
```suggestion
helppages.s helppages.h &: helppages.txt last-commit ../tools/paginate_help.py 
```

2024-03-17 14:11 UTC, pinobatch commented on gba/Makefile
> +CSFILES := posprintf.cS
What defines the `.cS` extension? It looks like it'd be used for source code in the C# language, especially on a case-insensitive file system such as default NTFS.

2024-03-17 14:44 UTC, Lorenzooone commented on gba/Makefile
> +vwf7.s vwf7.h: vwf7_cp144p.png ../tools/vwfbuild.py last-commit
While this is technically true, the fact that ".h" files are required to build before anything else in terms of ".s/.c/.cpp" files makes it so this is a non-issue.

2024-03-17 14:44 UTC, Lorenzooone commented on gba/Makefile
> +helppages.s helppages.h: helppages.txt last-commit ../tools/paginate_help.py
While this is technically true, the fact that ".h" files are required to build before anything else in terms of ".s/.c/.cpp" files makes it so this is a non-issue.

2024-03-17 14:47 UTC, Lorenzooone commented on gba/Makefile
> +CSFILES := posprintf.cS
.cS is supposed to stand for "compilable S" file. Considering how I also later changed ASFLAGS, this isn't needed anymore. It can be changed to a regular .s file.
This was done because ASFLAGS are ignored with .S files.

2024-03-17 15:04 UTC, Lorenzooone commented
The following Makefile rules already prevent such issues:
export OFILES_SOURCES := $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o) $(S_H_SFILES:.s=.o)

export HFILES := $(addsuffix .h,$(subst .,_,$(BINFILES))) $(subst .s,.h,$(S_H_SFILES))

$(OFILES_SOURCES) : $(HFILES)

In particular, in order to handle those ".s" files, the ".h" files must all be already built due to the last dependency rule.

2024-03-18 01:34 UTC, pinobatch commented
My reviewing this pull request is pending the expiration of an IP address ban imposed by devkitpro.org.

2024-03-18 03:12 UTC, merged

2024-03-18 16:35 UTC, pinobatch reviewed
lgtm

2024-03-18 16:37 UTC, pinobatch reviewed
I'm having trouble finding what button marks this PR as "looks good to me."

2024-03-18 16:56 UTC, pinobatch reviewed
Again, looks good to me. This time, I am trying checking the "Viewed" checkbox for each of the 20 changed files. If this review still results in "Changes requested" then I am going to have to ask someone on the gbadev Discord server for help in operating GitHub's user interface.

2024-03-18 16:56 UTC, pinobatch reviewed
It's still saying "changes requested".

2024-03-18 17:10 UTC, AntonioND approved these changes
Test